# action.yml
apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: 'platform-action-maven'
description: 'using maven to build Java application'
inputs:
  target:  # the target to build
    description: 'which target to build'
    required: true
    default: 'install'
  project-folder:  # the folder of the project
    description: 'the folder containing the pom.xml file'
    required: true
    default: ''
  #dest-folder:  # the folder of binary files
  #  description: 'the folder containing the artifacts for deployment'
  #  required: true
  #  default: ''
outputs:
  dest-folder:  # the folder of artifacts
    description: 'the folder containing the artifacts for deployment'
runs:
  using: composite
  steps:
    - id: build
      name: "build application"
      uses: docker://maven:latest
      run: |
        cd $SOURCE_FOLDER
        chmod a+x ./mvnw
        ./mvnw $TARGET
        printf "$SOURCE_FOLDER/target" > $CLOUDBEES_OUTPUTS/dest-folder
      env:
        TARGET: ${{ inputs.target }}
        SOURCE_FOLDER: ${{ inputs.project-folder }}

